### USER REQUESTS


### CREATE USER
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "dano@gmail.com",
  "password": "15646"
}

### FIND A PARTICULAR USER WITH A GIVEN ID
GET http://localhost:3000/auth/5

### FIND ALL USERS WITH A GIVEN EMAIL
GET http://localhost:3000/auth?email=brankohozza@gmail.com

### REMOVE A PARTICULAR USER WITH A GIVEN ID
DELETE http://localhost:3000/auth/2

### UPDATE A PARTICULAR USER WITH A GIVEN ID
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
  "email":"dada@haha.com"
}